name: Publish to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  publish-gh-pages:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Node.js version
        id: nvm
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
      - name: Install Yarn
        run: corepack enable
      - run: yarn --immutable
      - uses: MetaMask/action-publish-gh-pages@v1
        with:
          npm-build-command: demo:all
          directory: demo/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
