name: Publish to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  publish-gh-pages:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Corepack via Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: Install Yarn
        run: corepack enable
      - run: yarn --immutable
      - uses: MetaMask/action-publish-gh-pages@v1
        with:
          npm-build-command: demo:all
          directory: demo/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
